server:
  port: 7001

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 47.101.186.136:8848

    gateway:
      # 网关路由配置
      routes:
        # 路由id，自定义，只要唯一即可
        - id: order-service
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http 就是固定地址
          # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          uri: lb://order-service
          # 路由断言，也就是判断请求是否符合路由规则的条件
          predicates:
            # 这个是按照路径匹配，只要以 /order/ 开头就符合要求
            - Path=/order/**
#            - After=2037-01-20T17:42:47.789-07:00[America/Denver]
          # 过滤器：进入网关的请求和微服务返回的响应做处理
          filters:
            - AddRequestHeader=token, t2hdrwe4534ad
      # 默认过滤器：对所有的路由都生效
      default-filters:
        - AddRequestHeader=uuid, u345345
      # 全局的跨域处理
      globalcors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            # 允许哪些网站的跨域请求
            allowedOrigins:
              - "http://localhost:8090"
            # 允许的跨域ajax的请求方式
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            # 允许在请求中携带的头信息
            allowedHeaders: "*"
            # 是否允许携带cookie
            allowCredentials: true
            # 这次跨域检测的有效期
            maxAge: 360000